fix: image inclusion in subdirectories
DCsunset/pandoc-include pull request #55
Opened 2024-08-02 21:18 UTC by FynnFreyer

replace relative image paths with absolute ones
closes #54

2024-08-02 21:31 UTC, FynnFreyer commented
yikes, forgot to delete the `os.path.join` bit, so I had to force push over it

2024-08-04 13:16 UTC, DCsunset requested changes

2024-08-04 13:16 UTC, DCsunset commented on pandoc_include/main.py
> +        elem.url = os.path.abspath(url)
Please see https://github.com/DCsunset/pandoc-include/issues/54#issuecomment-2266328622

2024-08-04 16:33 UTC, DCsunset commented
Should be fixed already in the master branch.

2024-08-04 16:33 UTC, closed without merging